In [2]:
import numpy as np
a= np. array((1,2,3,4,5))
print (a)

[1 2 3 4 5]


In [3]:
import numpy as np
b= np.array([[1,2,3,4],[5,6,7,8]])
print (b)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
import numpy as np
c= np.zeros((3,5))
print (c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
import numpy as np
arr= np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr= arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [9]:
flat=arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [10]:
d=np.random.random((3,4))
print(d)

[[0.8631537  0.17361861 0.80362162 0.78200534]
 [0.05254375 0.86715463 0.45164915 0.98997649]
 [0.85824483 0.27198893 0.80293066 0.72208325]]


In [11]:
import numpy as np
e=np.arange (0,20,5)
print(e)

[ 0  5 10 15]


In [13]:
import numpy as np
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 4)
12
int64
2
